### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by MikeTMP** [FTBTeam/FTB-Academy#113]
1) I know this is the issue page, I just didn't know how to suggest mods.
2) Here's the list of mods you could implement:
- Mystical Agricolture
- Pam's harvestcraft
- SleepingOverhaul
- OldCombat & BetterCombat (Optional)
- Torcherino (Optional)
These are all user friendly mods and are compatible with almost everything. They are very easy to understand and with some good quests they it will be even easier to do so. Hope you see this and accept at least some of the mods i suggested.

**Comment by aaronhowser1** [comment]
This is the right place for mod suggestions, don't worry.

However, I don't think any of these should be in the pack. I'll go point by point for each.
* This is actually the only one of these I think may have a shot, you can make a new issue for it if you want. Problem is, it's too OP and not used in a bunch of packs so it doesn't fit here.
* Too complicated, it'll scare off new players. Also, we just really don't like the mod honestly. That's why we have XL Food Mod, it's small and simple and just adds food.
* Never heard of it. It looks interesting but it isn't for this pack. Keeping it in mind for other packs though!
* [This is the way combat is, gotta live with it.](https://www.youtube.com/watch?v=ta41xU-tkFA)
* Too OP, not widely used enough.
