### ISSUE TITLE
Turned off computer while running modpack, caused Ender Storage crashes, sent back to tutorial, and all RS items deleted

### ISSUE THREAD

**Issue by xLauke** [FTBTeam/FTB-Academy#181]
I tried deleting the mod and reinstalling it and that didnt work, so i dont know what else to do.
https://paste.dimdev.org/veluhuniti.mccrash

**Comment by aaronhowser1** [comment]
> EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\jblei\Twitch\Minecraft\Instances\FTB Academy\saves\New World\EnderStorage and start the server again.

Have you tried deleting that folder?

**Comment by xLauke** [comment]
I just did that and it put me in the tutorial so i did /quit_school and it got rid of all the items in my inventory and my storage disk have no items in them now

**Comment by aaronhowser1** [comment]
What happened that caused this? Did your computer turn off while playing or something, like a power outage? 

Were your storage disks in your inventory at the time? Or were they in your RS system? If this is because of a power outage or something, there really isn't something we can do to fix this as far as I know. I'll ping @LatvianModder, who's the dev for the school island mod though.

**Comment by xLauke** [comment]
My computer froze so i turned it off. My storage disk were in my disk drive.

**Comment by aaronhowser1** [comment]
You can check the backups folder in the modpack, there might be an older version of your world there you can extract and play. Other than that, there's not really much we can do. Don't turn off the computer while the game is running, it will always break things in any modpack.
