### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by Galacton** [FTBTeam/FTB-Academy#207]
Could you add Extra Utilities 2, /dank/null, and (if possible) Ender IO. I know Ender IO and Extra Utilities are big mods but they'd be appreciated.

**Comment by aaronhowser1** [comment]
* Extra Utilities 2
No. We used to have it but we removed it. The mod is buggy and hasn't updated since February, and it's confusing for new players.

* /dank/null
We also used to have this, but we removed it because of the whole thing with p455w0rd deleting the mod entirely. The mod is back, but we haven't decided either way yet. 

* Ender IO
No. The mod is too big and has too much overlap with mods that are already in. Also, it's just really weird. I personally don't like the new recipes in the 1.12 version, they have way too many steps.

We want to keep the mod count low in general. The only content mod we're adding any time soon will be Simply Jetpacks 2.
![image](https://user-images.githubusercontent.com/15698722/68739758-3718a880-05af-11ea-9226-f9c125e637ca.png)
