### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kooldud6789** [FTBTeam/FTB-Academy#324]
On The Academy mod pack yall offer i got pretty far and i was currently in a maze in the twilight forest then i logged off, when i logged back on the game wasnt letting me walk straight w was back and left D was forward and right A right and forward and s was left and back. i tried resetting the control setting even though i never touched them to begin with but that didnt work. and on top of that it was saying i was looking in all diffrent directions when my screen was saying otherwise and i couldnt break anyblock. i was going to try seeing if going through the portal would help but i couldnt get there. i then tried to make a new world and then i found out that the bug was on there too.

**Comment by aaronhowser1** [comment]
Now with punctuation:


> When I logged in the game wasnt letting me walk straight.
W was back and left
D was forward and right
A right and forward
S was left and back.
I tried resetting the control setting even though i never touched them to begin with but that didnt work. And on top of that it was saying I was looking in all different directions when my screen was saying otherwise and I couldn't break any block. i was going to try seeing if going through the portal would help but i couldnt get there. i then tried to make a new world and then i found out that the bug was on there too.

So you can only walk diagonally?

And what do you mean "it was saying I was looking in all different directions when my screen was saying otherwise" **What** was saying you were looking everywhere? Was the camera spinning? What do you mean the screen was saying otherwise?

Does this happen on new modpack installations? Try a different modpack too, see if it happens there.

**Comment by Kooldud6789** [comment]
when i said it wasnt looking where i was looking i could be looking down the maze hall and it would be saying i was looking at the brick block, then a cobblestone wall ect when i was looking down a hallway where i shouldnt have anything popping up. and yes i could only walk diagonally. and no it was only on that one mod pack

**Comment by aaronhowser1** [comment]
**What** was saying anything? What saying you were looking at a brick wall? I have no idea what you're talking about at all.
