### ISSUE TITLE
During installation from twitch, access is denied.

### ISSUE THREAD

**Issue by shahe4** [FTBTeam/FTB-Academy#7]
* **Modpack Version**: 

* **Issue**: 

whenever I try to download the mod from the twitch mac os app, I get the error message detailed above. I tried installing other modpacks and there is no problem with that, and I can also install individual mods. I am not too sure what I can do to fix this but I'd like to learn common ftb mods. id love any advice thanks.
* **Link to Log or Crash File Paste**: 
Access to the path "/var/folders/m8/xq1vxyg9247btrqc7tg1hl800000gn/T/Curse Client/52B97AA4A50E48B9B8D8A0D972C4F4F6/2/manifest.json" or "/Users/shah/Twitch/Minecraft/Instances/FTB Academy/manifest.json" is denied
* **Is it Repeatable?**: 
yes
* **Mod/s Affected**: 
all
* **Known Fix**:

**Comment by TroutPlayz** [comment]
im having the same problem

**Comment by PewDeePie** [comment]
Same see

**Comment by Sunekaer** [comment]
Not an issue i have seen before and sadly not one I can help with, you need to contact twitch as this is a launcher issue

**Comment by aaronhowser1** [comment]
You can try restarting Twitch or your computer and trying again, but there really isn't anything we can do about it, sorry

**Comment by diego898** [comment]
I went searching in both of those paths for that file and that file does not exist there. 

My error message: `Access to the path "/var/folders/g2/7_gg0_851rb_7qdyjmm_gr4m0000gn/T/Curse Client/6592213BAB9345C58FDCB5B0A7B681BC/2/manifest.json" or "/Users/myname/Twitch/Minecraft/Instances/FTB Academy/manifest.json" is denied.`


At`/var/folders/.../2/`:
```
find . -iname "manifest*"
./overrides/config/brandon3055/ProjectIntelligence/DocUpdater/manifest.json
./overrides/config/brandon3055/ProjectIntelligence/manifest.json
```

Since this was my first modpack, `/Users/.../Twitch/Minecraft/Instances/` is empty. 

Restarting twitch, and my computer, did not fix this problem. 

I was able to succesfully install FTB Ultimate Reloaded. After doing so I have:
```
find . -iname "manifest.json"
./FTB Ultimate Reloaded/manifest.json
```
which is expected. 

I think this is only a problem when installing this mod!
